#
# Copyright 2022-2023 benelog GmbH & Co. KG
#
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.
#

quarkus:
  swagger-ui:
    always-include: true
    title: "OpenAPI Event Hash Service"
    footer: "&#169; 2020-2023 - benelog GmbH & Co KG"

  http:
    cors:
      ~: true
      methods: GET,POST
      origins: "/.*/"
    port: 9000

  container-image:
    group: openepcis
    name: event-hash-generator-service
    additional-tags:
      - latest

  native:
    resources:
      includes: "1.2/EPCIS/**,2.0/EPCIS/**"
  banner:
    path: "openepcis-banner.txt"


mp:
  openapi:
    filter: "io.openepcis.resources.oas.EPCISExampleOASFilter"

    extensions:
      smallrye:
        info:
          title: "OpenEPCIS Event Hash Service API"
          version: "1.0.0"
          description: "The EPCIS Event Hash is a unique digital fingerprint generated for supply chain events. It's based on the EPCIS (Electronic Product Code Information Services) standard, which tracks the movement and status of goods. The hash ensures data integrity and simplifies event verification and tracking in supply chains."
          contact:
            email: "info@openepcis.io"
            name: "OpenEPCIS | benelog GmbH & Co. KG"
            url: "https://openepcis.io"
            license:
              name: "Apache 2.0"
              url: "http://www.apache.org/licenses/LICENSE-2.0.html"
