quarkus:
  swagger-ui:
    always-include: true
  http:
    cors:
      ~: true
      methods: GET,POST
      origins: "/.*/"
    port: 9000

  container-image:
    group: openepcis
    name: event-hash-generator-service
    additional-tags:
      - latest
mp:
  openapi:
    filter: "io.openepcis.resources.oas.EPCISExampleOASFilter"
